/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Grib.Api.Interop.SWIG {

public class GribUtilGridSpec : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GribUtilGridSpec(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GribUtilGridSpec obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GribUtilGridSpec() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GribApiProxyPINVOKE.delete_GribUtilGridSpec(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int gridType {
	set
	{
		GribApiProxyPINVOKE.GribUtilGridSpec_gridType_set(swigCPtr, value);
	} 
	get
	{
		return GribApiProxyPINVOKE.GribUtilGridSpec_gridType_get(swigCPtr);
	} 
  }

  public int ni {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_ni_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_ni_get(swigCPtr);
      return ret;
    } 
  }

  public int nj {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_nj_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_nj_get(swigCPtr);
      return ret;
    } 
  }

  public double iDirectionIncrementInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_iDirectionIncrementInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_iDirectionIncrementInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double jDirectionIncrementInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_jDirectionIncrementInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_jDirectionIncrementInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double longitudeOfFirstGridPointInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double longitudeOfLastGridPointInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfLastGridPointInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfLastGridPointInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double latitudeOfFirstGridPointInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double latitudeOfLastGridPointInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfLastGridPointInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfLastGridPointInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public int uvRelativeToGrid {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_uvRelativeToGrid_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_uvRelativeToGrid_get(swigCPtr);
      return ret;
    } 
  }

  public double latitudeOfSouthernPoleInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public double longitudeOfSouthernPoleInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public int iScansNegatively {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_iScansNegatively_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_iScansNegatively_get(swigCPtr);
      return ret;
    } 
  }

  public int jScansPositively {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_jScansPositively_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_jScansPositively_get(swigCPtr);
      return ret;
    } 
  }

  public int n {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_n_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_n_get(swigCPtr);
      return ret;
    } 
  }

  public int bitmapPresent {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_bitmapPresent_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_bitmapPresent_get(swigCPtr);
      return ret;
    } 
  }

  public double missingValue {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_missingValue_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_missingValue_get(swigCPtr);
      return ret;
    } 
  }

  public int[] pl {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_pl_set(swigCPtr, value);
    } 
	get
	{
		return GribApiProxyPINVOKE.GribUtilGridSpec_pl_get(swigCPtr);
	} 
  }

  public int plSize {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_plSize_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_plSize_get(swigCPtr);
      return ret;
    } 
  }

  public int truncation {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_truncation_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_truncation_get(swigCPtr);
      return ret;
    } 
  }

  public double orientationOfTheGridInDegrees {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_orientationOfTheGridInDegrees_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilGridSpec_orientationOfTheGridInDegrees_get(swigCPtr);
      return ret;
    } 
  }

  public int dyInMetres {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_dyInMetres_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_dyInMetres_get(swigCPtr);
      return ret;
    } 
  }

  public int dxInMetres {
    set {
      GribApiProxyPINVOKE.GribUtilGridSpec_dxInMetres_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilGridSpec_dxInMetres_get(swigCPtr);
      return ret;
    } 
  }

  public GribUtilGridSpec() : this(GribApiProxyPINVOKE.new_GribUtilGridSpec(), true) {
  }

}

}
