/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Grib.Api.Interop.SWIG {

public class grib_string_list : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal grib_string_list(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(grib_string_list obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~grib_string_list() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GribApiProxyPINVOKE.delete_grib_string_list(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string value {
    set {
      GribApiProxyPINVOKE.grib_string_list_value_set(swigCPtr, value);
    } 
    get {
      string ret = GribApiProxyPINVOKE.grib_string_list_value_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_grib_string_list next {
    set {
      GribApiProxyPINVOKE.grib_string_list_next_set(swigCPtr, SWIGTYPE_p_grib_string_list.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = GribApiProxyPINVOKE.grib_string_list_next_get(swigCPtr);
      SWIGTYPE_p_grib_string_list ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_grib_string_list(cPtr, false);
      return ret;
    } 
  }

  public grib_string_list() : this(GribApiProxyPINVOKE.new_grib_string_list(), true) {
  }

}

}
