/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Grib.Api.Interop.SWIG {

class GribApiProxyPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="SWIGRegisterExceptionCallbacks_GribApiProxy")]
    public static extern void SWIGRegisterExceptionCallbacks_GribApiProxy(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_GribApiProxy")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_GribApiProxy(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_GribApiProxy(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_GribApiProxy(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(GribApiProxyPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(GribApiProxyPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="SWIGRegisterStringCallback_GribApiProxy")]
    public static extern void SWIGRegisterStringCallback_GribApiProxy(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_GribApiProxy(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SECTION_PRODUCT_get")]
  public static extern int GRIB_SECTION_PRODUCT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SECTION_GRID_get")]
  public static extern int GRIB_SECTION_GRID_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SECTION_LOCAL_get")]
  public static extern int GRIB_SECTION_LOCAL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SECTION_DATA_get")]
  public static extern int GRIB_SECTION_DATA_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SECTION_BITMAP_get")]
  public static extern int GRIB_SECTION_BITMAP_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_LOG_INFO_get")]
  public static extern int GRIB_LOG_INFO_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_LOG_WARNING_get")]
  public static extern int GRIB_LOG_WARNING_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_LOG_ERROR_get")]
  public static extern int GRIB_LOG_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_LOG_FATAL_get")]
  public static extern int GRIB_LOG_FATAL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_LOG_DEBUG_get")]
  public static extern int GRIB_LOG_DEBUG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_MISSING_LONG_get")]
  public static extern int GRIB_MISSING_LONG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_MISSING_DOUBLE_get")]
  public static extern double GRIB_MISSING_DOUBLE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_SET_SPEC_FLAGS_ONLY_PACKING_get")]
  public static extern int GRIB_UTIL_SET_SPEC_FLAGS_ONLY_PACKING_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_READ_ONLY_get")]
  public static extern int GRIB_DUMP_FLAG_READ_ONLY_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_DUMP_OK_get")]
  public static extern int GRIB_DUMP_FLAG_DUMP_OK_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_VALUES_get")]
  public static extern int GRIB_DUMP_FLAG_VALUES_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_CODED_get")]
  public static extern int GRIB_DUMP_FLAG_CODED_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_OCTECT_get")]
  public static extern int GRIB_DUMP_FLAG_OCTECT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_ALIASES_get")]
  public static extern int GRIB_DUMP_FLAG_ALIASES_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_TYPE_get")]
  public static extern int GRIB_DUMP_FLAG_TYPE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_HEXADECIMAL_get")]
  public static extern int GRIB_DUMP_FLAG_HEXADECIMAL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_NO_DATA_get")]
  public static extern int GRIB_DUMP_FLAG_NO_DATA_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DUMP_FLAG_ALL_DATA_get")]
  public static extern int GRIB_DUMP_FLAG_ALL_DATA_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NEAREST_SAME_GRID_get")]
  public static extern int GRIB_NEAREST_SAME_GRID_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NEAREST_SAME_DATA_get")]
  public static extern int GRIB_NEAREST_SAME_DATA_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NEAREST_SAME_POINT_get")]
  public static extern int GRIB_NEAREST_SAME_POINT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetNewFromFiles")]
  public static extern global::System.IntPtr GribFieldsetNewFromFiles(System.Runtime.InteropServices.HandleRef jarg1, string[] jarg2, int jarg3, string[] jarg4, int jarg5, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg6, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg7, out int jarg8);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetDelete")]
  public static extern void GribFieldsetDelete(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetRewind")]
  public static extern void GribFieldsetRewind(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetApplyOrderBy")]
  public static extern int GribFieldsetApplyOrderBy(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetNextHandle")]
  public static extern System.IntPtr GribFieldsetNextHandle(global::System.Runtime.InteropServices.HandleRef jarg1, out int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribFieldsetCount")]
  public static extern int GribFieldsetCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribValuesCheck")]
  public static extern int GribValuesCheck(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexNewFromFile")]
  public static extern global::System.IntPtr GribIndexNewFromFile(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexNew")]
  public static extern global::System.IntPtr GribIndexNew(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexAddFile")]
  public static extern int GribIndexAddFile(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexWrite")]
  public static extern int GribIndexWrite(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexRead")]
  public static extern global::System.IntPtr GribIndexRead(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexGetSize")]
  public static extern int GribIndexGetSize(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexGetLong")]
  public static extern int GribIndexGetLong(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexGetDouble")]
  public static extern int GribIndexGetDouble(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexGetString")]
  public static extern int GribIndexGetString(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out System.Text.StringBuilder jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexSelectLong")]
  public static extern int GribIndexSelectLong(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexSelectDouble")]
  public static extern int GribIndexSelectDouble(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexSelectString")]
  public static extern int GribIndexSelectString(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromIndex")]
  public static extern System.IntPtr GribHandleNewFromIndex(global::System.Runtime.InteropServices.HandleRef jarg1, out int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIndexDelete")]
  public static extern void GribIndexDelete(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribCountInFile")]
  public static extern int GribCountInFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromFile")]
  public static extern System.IntPtr GribHandleNewFromFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribWriteMessage")]
  public static extern int GribWriteMessage(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribStringList_value_set")]
  public static extern void GribStringList_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribStringList_value_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribStringList_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribStringList_next_set")]
  public static extern void GribStringList_next_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribStringList_next_get")]
  public static extern global::System.IntPtr GribStringList_next_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_new_GribStringList")]
  public static extern global::System.IntPtr new_GribStringList();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_delete_GribStringList")]
  public static extern void delete_GribStringList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilSectionsCopy")]
  public static extern System.IntPtr GribUtilSectionsCopy(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, int jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGetParamId")]
  public static extern global::System.IntPtr GribUtilGetParamId([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGetMarsParam")]
  public static extern global::System.IntPtr GribUtilGetMarsParam([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromMessage")]
  public static extern System.IntPtr GribHandleNewFromMessage(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromMultiMessage")]
  public static extern System.IntPtr GribHandleNewFromMultiMessage(System.Runtime.InteropServices.HandleRef jarg1, out System.IntPtr jarg2, ref System.UIntPtr jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromMessageCopy")]
  public static extern System.IntPtr GribHandleNewFromMessageCopy(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromTemplate")]
  public static extern System.IntPtr GribHandleNewFromTemplate(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromSamples")]
  public static extern System.IntPtr GribHandleNewFromSamples(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleClone")]
  public static extern System.IntPtr GribHandleClone(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleDelete")]
  public static extern int GribHandleDelete(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiHandleNew")]
  public static extern global::System.IntPtr GribMultiHandleNew(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiHandleAppend")]
  public static extern int GribMultiHandleAppend(System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiHandleDelete")]
  public static extern int GribMultiHandleDelete(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiHandleWrite")]
  public static extern int GribMultiHandleWrite(global::System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetMessage")]
  public static extern int GribGetMessage(System.Runtime.InteropServices.HandleRef jarg1, out System.IntPtr jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetMessageCopy")]
  public static extern int GribGetMessageCopy(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorNew")]
  public static extern System.IntPtr GribIteratorNew(System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetData")]
  public static extern int GribGetData(System.Runtime.InteropServices.HandleRef jarg1, double[] jarg2, double[] jarg3, double[] jarg4, ref System.UIntPtr jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorNext")]
  public static extern int GribIteratorNext(System.Runtime.InteropServices.HandleRef jarg1, out double jarg2, out double jarg3, out double jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorPrevious")]
  public static extern int GribIteratorPrevious(System.Runtime.InteropServices.HandleRef jarg1, out double jarg2, out double jarg3, out double jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorHasNext")]
  public static extern int GribIteratorHasNext(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorReset")]
  public static extern int GribIteratorReset(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIteratorDelete")]
  public static extern int GribIteratorDelete(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribNearestNew")]
  public static extern global::System.IntPtr GribNearestNew(System.Runtime.InteropServices.HandleRef jarg1, out int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribNearestFind")]
  public static extern int GribNearestFind(global::System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, double jarg3, double jarg4, uint jarg5, double[] jarg6, double[] jarg7, double[] jarg8, double[] jarg9, int[] jarg10, ref System.UIntPtr jarg11);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribNearestDelete")]
  public static extern int GribNearestDelete(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribNearestFindMultiple")]
  public static extern int GribNearestFindMultiple(System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double[] jarg3, double[] jarg4, int jarg5, double[] jarg6, double[] jarg7, double[] jarg8, double[] jarg9, int[] jarg10);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetOffset")]
  public static extern int GribGetOffset(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetSize")]
  public static extern int GribGetSize(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetLength")]
  public static extern int GribGetLength(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetLong")]
  public static extern int GribGetLong(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetDouble")]
  public static extern int GribGetDouble(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetDoubleElement")]
  public static extern int GribGetDoubleElement(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int jarg3, out double jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetDoubleElements")]
  public static extern int GribGetDoubleElements(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4, out double jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetString")]
  public static extern int GribGetString(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, System.Text.StringBuilder jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetBytes")]
  public static extern int GribGetBytes(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, byte[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetDoubleArray")]
  public static extern int GribGetDoubleArray(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetLongArray")]
  public static extern int GribGetLongArray(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribCopyNamespace")]
  public static extern int GribCopyNamespace(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetLong")]
  public static extern int GribSetLong(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetDouble")]
  public static extern int GribSetDouble(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetString")]
  public static extern int GribSetString(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, string jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetBytes")]
  public static extern int GribSetBytes(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, byte[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetDoubleArray")]
  public static extern int GribSetDoubleArray(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double[] jarg3, System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetForceDoubleArray")]
  public static extern int GribSetForceDoubleArray(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, double[] jarg3, System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetLongArray")]
  public static extern int GribSetLongArray(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int[] jarg3, System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribDumpContent")]
  public static extern void GribDumpContent(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg3, uint jarg4, byte[] jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribDumpActionTree")]
  public static extern void GribDumpActionTree(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextGetDefault")]
  public static extern System.IntPtr GribContextGetDefault();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextNew")]
  public static extern System.IntPtr GribContextNew(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextDelete")]
  public static extern void GribContextDelete(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGtsHeaderOn")]
  public static extern void GribGtsHeaderOn(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGtsHeaderOff")]
  public static extern void GribGtsHeaderOff(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGribexModeOn")]
  public static extern void GribGribexModeOn(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetGribexMode")]
  public static extern int GribGetGribexMode(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGribexModeOff")]
  public static extern void GribGribexModeOff(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextSetMemoryProc")]
  public static extern void GribContextSetMemoryProc(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextSetPersistentMemoryProc")]
  public static extern void GribContextSetPersistentMemoryProc(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextSetBufferMemoryProc")]
  public static extern void GribContextSetBufferMemoryProc(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextSetPrintProc")]
  public static extern void GribContextSetPrintProc(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribContextSetLoggingProc")]
  public static extern void GribContextSetLoggingProc(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiSupportOn")]
  public static extern void GribMultiSupportOn(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiSupportOff")]
  public static extern void GribMultiSupportOff(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribMultiSupportResetFile")]
  public static extern void GribMultiSupportResetFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSamplesPath")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribSamplesPath(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetApiVersion")]
  public static extern int GribGetApiVersion();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetGitSha1")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribGetGitSha1();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPrintApiVersion")]
  public static extern void GribPrintApiVersion(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorNew")]
  public static extern System.IntPtr GribKeysIteratorNew(System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorNext")]
  public static extern int GribKeysIteratorNext(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorGetName")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribKeysIteratorGetName(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorDelete")]
  public static extern int GribKeysIteratorDelete(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorRewind")]
  public static extern int GribKeysIteratorRewind(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorSetFlags")]
  public static extern int GribKeysIteratorSetFlags(System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorGetLong")]
  public static extern int GribKeysIteratorGetLong(System.Runtime.InteropServices.HandleRef jarg1, out int jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorGetDouble")]
  public static extern int GribKeysIteratorGetDouble(System.Runtime.InteropServices.HandleRef jarg1, out double jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorGetString")]
  public static extern int GribKeysIteratorGetString(System.Runtime.InteropServices.HandleRef jarg1, System.Text.StringBuilder jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribKeysIteratorGetBytes")]
  public static extern int GribKeysIteratorGetBytes(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUpdateSectionsLengths")]
  public static extern void GribUpdateSectionsLengths(System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetErrorMessage")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribGetErrorMessage(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetFailProc")]
  public static extern void GribSetFailProc(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetExitProc")]
  public static extern void GribSetExitProc(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribExit")]
  public static extern void GribExit(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetTypeName")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]
  public static extern string GribGetTypeName(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetNativeType")]
  public static extern int GribGetNativeType(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribCheck")]
  public static extern void GribCheck([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, int jarg3, int jarg4, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetValues")]
  public static extern int GribSetValues(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromPartialMessageCopy")]
  public static extern System.IntPtr GribHandleNewFromPartialMessageCopy(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribHandleNewFromPartialMessage")]
  public static extern System.IntPtr GribHandleNewFromPartialMessage(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIsMissing")]
  public static extern int GribIsMissing(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribIsDefined")]
  public static extern int GribIsDefined(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribSetMissing")]
  public static extern int GribSetMissing(System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr)]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetGaussianLatitudes")]
  public static extern int GribGetGaussianLatitudes(int jarg1, double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribJulianToDatetime")]
  public static extern int GribJulianToDatetime(double jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribDatetimeToJulian")]
  public static extern int GribDatetimeToJulian(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, global::System.Runtime.InteropServices.HandleRef jarg7);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribJulianToDate")]
  public static extern int GribJulianToDate(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribDateToJulian")]
  public static extern int GribDateToJulian(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetReducedRow")]
  public static extern void GribGetReducedRow(int jarg1, double jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadAnyFromFile")]
  public static extern int WmoReadAnyFromFile(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadGribFromFile")]
  public static extern int WmoReadGribFromFile(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadBufrFromFile")]
  public static extern int WmoReadBufrFromFile(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadGtsFromFile")]
  public static extern int WmoReadGtsFromFile(System.Runtime.InteropServices.HandleRef jarg1, byte[] jarg2, ref System.UIntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadAnyFromStream")]
  public static extern int WmoReadAnyFromStream(byte[] jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte[] jarg3, ref System.UIntPtr jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadAnyFromFileMalloc")]
  public static extern byte[] WmoReadAnyFromFileMalloc(System.Runtime.InteropServices.HandleRef jarg1, int jarg2, ref System.UIntPtr jarg3, ref System.UIntPtr jarg4, out int jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadGtsFromFileMalloc")]
  public static extern byte[] WmoReadGtsFromFileMalloc(System.Runtime.InteropServices.HandleRef jarg1, int jarg2, ref System.UIntPtr jarg3, ref System.UIntPtr jarg4, out int jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_WmoReadBufrFromFileMalloc")]
  public static extern byte[] WmoReadBufrFromFileMalloc(System.Runtime.InteropServices.HandleRef jarg1, int jarg2, ref System.UIntPtr jarg3, ref System.UIntPtr jarg4, out int jarg5);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_EccodeGtsNewFromFile")]
  public static extern System.IntPtr EccodeGtsNewFromFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, int jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_EccodeBufrNewFromFile")]
  public static extern System.IntPtr EccodeBufrNewFromFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, int jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_EccodeGribNewFromFile")]
  public static extern System.IntPtr EccodeGribNewFromFile(System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2, int jarg3, out int jarg4);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetMessageOffset")]
  public static extern int GribGetMessageOffset(System.Runtime.InteropServices.HandleRef jarg1, ref System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribGetMessageSize")]
  public static extern int GribGetMessageSize(System.Runtime.InteropServices.HandleRef jarg1, ref System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_context_set")]
  public static extern void GribPoints_context_set(global::System.Runtime.InteropServices.HandleRef jarg1, System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_context_get")]
  public static extern System.IntPtr GribPoints_context_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_latitudes_set")]
  public static extern void GribPoints_latitudes_set(global::System.Runtime.InteropServices.HandleRef jarg1, double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_latitudes_get")]
  public static extern double[] GribPoints_latitudes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_longitudes_set")]
  public static extern void GribPoints_longitudes_set(global::System.Runtime.InteropServices.HandleRef jarg1, double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_longitudes_get")]
  public static extern double[] GribPoints_longitudes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_indexes_set")]
  public static extern void GribPoints_indexes_set(global::System.Runtime.InteropServices.HandleRef jarg1, ref System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_indexes_get")]
  public static extern System.IntPtr GribPoints_indexes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_groupStart_set")]
  public static extern void GribPoints_groupStart_set(global::System.Runtime.InteropServices.HandleRef jarg1, ref System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_groupStart_get")]
  public static extern System.IntPtr GribPoints_groupStart_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_groupLen_set")]
  public static extern void GribPoints_groupLen_set(global::System.Runtime.InteropServices.HandleRef jarg1, ref System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_groupLen_get")]
  public static extern System.IntPtr GribPoints_groupLen_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_nGroups_set")]
  public static extern void GribPoints_nGroups_set(global::System.Runtime.InteropServices.HandleRef jarg1, System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_nGroups_get")]
  public static extern System.UIntPtr GribPoints_nGroups_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_n_set")]
  public static extern void GribPoints_n_set(global::System.Runtime.InteropServices.HandleRef jarg1, System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_n_get")]
  public static extern System.UIntPtr GribPoints_n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_size_set")]
  public static extern void GribPoints_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, System.UIntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPoints_size_get")]
  public static extern System.UIntPtr GribPoints_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_new_GribPoints")]
  public static extern global::System.IntPtr new_GribPoints();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_delete_GribPoints")]
  public static extern void delete_GribPoints(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribBoxNew")]
  public static extern global::System.IntPtr GribBoxNew(System.Runtime.InteropServices.HandleRef jarg1, out int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribBoxGetPoints")]
  public static extern global::System.IntPtr GribBoxGetPoints(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, out int jarg6);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribPointsGetValues")]
  public static extern int GribPointsGetValues(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, out double jarg3);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_REGULAR_LL_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_REGULAR_LL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_ROTATED_LL_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_ROTATED_LL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_REGULAR_GG_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_REGULAR_GG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_ROTATED_GG_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_ROTATED_GG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_REDUCED_GG_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_REDUCED_GG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_SH_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_SH_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_REDUCED_LL_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_REDUCED_LL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_POLAR_STEREOGRAPHIC_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_POLAR_STEREOGRAPHIC_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_GRID_SPEC_REDUCED_ROTATED_GG_get")]
  public static extern int GRIB_UTIL_GRID_SPEC_REDUCED_ROTATED_GG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_gridType_set")]
  public static extern void GribUtilGridSpec_gridType_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_gridType_get")]
  public static extern int GribUtilGridSpec_gridType_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_ni_set")]
  public static extern void GribUtilGridSpec_ni_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_ni_get")]
  public static extern int GribUtilGridSpec_ni_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_nj_set")]
  public static extern void GribUtilGridSpec_nj_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_nj_get")]
  public static extern int GribUtilGridSpec_nj_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_iDirectionIncrementInDegrees_set")]
  public static extern void GribUtilGridSpec_iDirectionIncrementInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_iDirectionIncrementInDegrees_get")]
  public static extern double GribUtilGridSpec_iDirectionIncrementInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_jDirectionIncrementInDegrees_set")]
  public static extern void GribUtilGridSpec_jDirectionIncrementInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_jDirectionIncrementInDegrees_get")]
  public static extern double GribUtilGridSpec_jDirectionIncrementInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_set")]
  public static extern void GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_get")]
  public static extern double GribUtilGridSpec_longitudeOfFirstGridPointInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfLastGridPointInDegrees_set")]
  public static extern void GribUtilGridSpec_longitudeOfLastGridPointInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfLastGridPointInDegrees_get")]
  public static extern double GribUtilGridSpec_longitudeOfLastGridPointInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_set")]
  public static extern void GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_get")]
  public static extern double GribUtilGridSpec_latitudeOfFirstGridPointInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfLastGridPointInDegrees_set")]
  public static extern void GribUtilGridSpec_latitudeOfLastGridPointInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfLastGridPointInDegrees_get")]
  public static extern double GribUtilGridSpec_latitudeOfLastGridPointInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_uvRelativeToGrid_set")]
  public static extern void GribUtilGridSpec_uvRelativeToGrid_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_uvRelativeToGrid_get")]
  public static extern int GribUtilGridSpec_uvRelativeToGrid_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_set")]
  public static extern void GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_get")]
  public static extern double GribUtilGridSpec_latitudeOfSouthernPoleInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_set")]
  public static extern void GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_get")]
  public static extern double GribUtilGridSpec_longitudeOfSouthernPoleInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_iScansNegatively_set")]
  public static extern void GribUtilGridSpec_iScansNegatively_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_iScansNegatively_get")]
  public static extern int GribUtilGridSpec_iScansNegatively_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_jScansPositively_set")]
  public static extern void GribUtilGridSpec_jScansPositively_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_jScansPositively_get")]
  public static extern int GribUtilGridSpec_jScansPositively_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_n_set")]
  public static extern void GribUtilGridSpec_n_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_n_get")]
  public static extern int GribUtilGridSpec_n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_bitmapPresent_set")]
  public static extern void GribUtilGridSpec_bitmapPresent_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_bitmapPresent_get")]
  public static extern int GribUtilGridSpec_bitmapPresent_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_missingValue_set")]
  public static extern void GribUtilGridSpec_missingValue_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_missingValue_get")]
  public static extern double GribUtilGridSpec_missingValue_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_pl_set")]
  public static extern void GribUtilGridSpec_pl_set(global::System.Runtime.InteropServices.HandleRef jarg1, int[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_pl_get")]
  public static extern int[] GribUtilGridSpec_pl_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_plSize_set")]
  public static extern void GribUtilGridSpec_plSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_plSize_get")]
  public static extern int GribUtilGridSpec_plSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_truncation_set")]
  public static extern void GribUtilGridSpec_truncation_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_truncation_get")]
  public static extern int GribUtilGridSpec_truncation_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_orientationOfTheGridInDegrees_set")]
  public static extern void GribUtilGridSpec_orientationOfTheGridInDegrees_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_orientationOfTheGridInDegrees_get")]
  public static extern double GribUtilGridSpec_orientationOfTheGridInDegrees_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_dyInMetres_set")]
  public static extern void GribUtilGridSpec_dyInMetres_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_dyInMetres_get")]
  public static extern int GribUtilGridSpec_dyInMetres_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_dxInMetres_set")]
  public static extern void GribUtilGridSpec_dxInMetres_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilGridSpec_dxInMetres_get")]
  public static extern int GribUtilGridSpec_dxInMetres_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_new_GribUtilGridSpec")]
  public static extern global::System.IntPtr new_GribUtilGridSpec();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_delete_GribUtilGridSpec")]
  public static extern void delete_GribUtilGridSpec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_SAME_AS_INPUT_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_SAME_AS_INPUT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_SPECTRAL_COMPLEX_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_SPECTRAL_COMPLEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_SPECTRAL_SIMPLE_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_SPECTRAL_SIMPLE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_JPEG_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_JPEG_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_GRID_COMPLEX_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_GRID_COMPLEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_GRID_SIMPLE_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_GRID_SIMPLE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_GRID_SIMPLE_MATRIX_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_GRID_SIMPLE_MATRIX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_TYPE_GRID_SECOND_ORDER_get")]
  public static extern int GRIB_UTIL_PACKING_TYPE_GRID_SECOND_ORDER_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_SAME_AS_INPUT_get")]
  public static extern int GRIB_UTIL_PACKING_SAME_AS_INPUT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_PACKING_USE_PROVIDED_get")]
  public static extern int GRIB_UTIL_PACKING_USE_PROVIDED_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_ACCURACY_SAME_BITS_PER_VALUES_AS_INPUT_get")]
  public static extern int GRIB_UTIL_ACCURACY_SAME_BITS_PER_VALUES_AS_INPUT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_ACCURACY_USE_PROVIDED_BITS_PER_VALUES_get")]
  public static extern int GRIB_UTIL_ACCURACY_USE_PROVIDED_BITS_PER_VALUES_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_ACCURACY_SAME_DECIMAL_SCALE_FACTOR_AS_INPUT_get")]
  public static extern int GRIB_UTIL_ACCURACY_SAME_DECIMAL_SCALE_FACTOR_AS_INPUT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UTIL_ACCURACY_USE_PROVIDED_DECIMAL_SCALE_FACTOR_get")]
  public static extern int GRIB_UTIL_ACCURACY_USE_PROVIDED_DECIMAL_SCALE_FACTOR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_packingType_set")]
  public static extern void GribUtilPackingSpec_packingType_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_packingType_get")]
  public static extern int GribUtilPackingSpec_packingType_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_packing_set")]
  public static extern void GribUtilPackingSpec_packing_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_packing_get")]
  public static extern int GribUtilPackingSpec_packing_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_boustrophedonic_set")]
  public static extern void GribUtilPackingSpec_boustrophedonic_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_boustrophedonic_get")]
  public static extern int GribUtilPackingSpec_boustrophedonic_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_editionNumber_set")]
  public static extern void GribUtilPackingSpec_editionNumber_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_editionNumber_get")]
  public static extern int GribUtilPackingSpec_editionNumber_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_accuracy_set")]
  public static extern void GribUtilPackingSpec_accuracy_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_accuracy_get")]
  public static extern int GribUtilPackingSpec_accuracy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_bitsPerValue_set")]
  public static extern void GribUtilPackingSpec_bitsPerValue_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_bitsPerValue_get")]
  public static extern int GribUtilPackingSpec_bitsPerValue_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_decimalScaleFactor_set")]
  public static extern void GribUtilPackingSpec_decimalScaleFactor_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_decimalScaleFactor_get")]
  public static extern int GribUtilPackingSpec_decimalScaleFactor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_computeLaplacianOperator_set")]
  public static extern void GribUtilPackingSpec_computeLaplacianOperator_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_computeLaplacianOperator_get")]
  public static extern int GribUtilPackingSpec_computeLaplacianOperator_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_truncateLaplacian_set")]
  public static extern void GribUtilPackingSpec_truncateLaplacian_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_truncateLaplacian_get")]
  public static extern int GribUtilPackingSpec_truncateLaplacian_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_laplacianOperator_set")]
  public static extern void GribUtilPackingSpec_laplacianOperator_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_laplacianOperator_get")]
  public static extern double GribUtilPackingSpec_laplacianOperator_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_deleteLocalDefinition_set")]
  public static extern void GribUtilPackingSpec_deleteLocalDefinition_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_deleteLocalDefinition_get")]
  public static extern int GribUtilPackingSpec_deleteLocalDefinition_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_extraSettings_set")]
  public static extern void GribUtilPackingSpec_extraSettings_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_extraSettings_get")]
  public static extern global::System.IntPtr GribUtilPackingSpec_extraSettings_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_extraSettingsCount_set")]
  public static extern void GribUtilPackingSpec_extraSettingsCount_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilPackingSpec_extraSettingsCount_get")]
  public static extern int GribUtilPackingSpec_extraSettingsCount_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_new_GribUtilPackingSpec")]
  public static extern global::System.IntPtr new_GribUtilPackingSpec();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_delete_GribUtilPackingSpec")]
  public static extern void delete_GribUtilPackingSpec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GribUtilSetSpec")]
  public static extern System.IntPtr GribUtilSetSpec(System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4, double[] jarg5, System.UIntPtr jarg6, out int jarg7);

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SUCCESS_get")]
  public static extern int GRIB_SUCCESS_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_END_OF_FILE_get")]
  public static extern int GRIB_END_OF_FILE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INTERNAL_ERROR_get")]
  public static extern int GRIB_INTERNAL_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_BUFFER_TOO_SMALL_get")]
  public static extern int GRIB_BUFFER_TOO_SMALL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NOT_IMPLEMENTED_get")]
  public static extern int GRIB_NOT_IMPLEMENTED_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_7777_NOT_FOUND_get")]
  public static extern int GRIB_7777_NOT_FOUND_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_ARRAY_TOO_SMALL_get")]
  public static extern int GRIB_ARRAY_TOO_SMALL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_FILE_NOT_FOUND_get")]
  public static extern int GRIB_FILE_NOT_FOUND_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_CODE_NOT_FOUND_IN_TABLE_get")]
  public static extern int GRIB_CODE_NOT_FOUND_IN_TABLE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_ARRAY_SIZE_get")]
  public static extern int GRIB_WRONG_ARRAY_SIZE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NOT_FOUND_get")]
  public static extern int GRIB_NOT_FOUND_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_IO_PROBLEM_get")]
  public static extern int GRIB_IO_PROBLEM_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_MESSAGE_get")]
  public static extern int GRIB_INVALID_MESSAGE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DECODING_ERROR_get")]
  public static extern int GRIB_DECODING_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_ENCODING_ERROR_get")]
  public static extern int GRIB_ENCODING_ERROR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NO_MORE_IN_SET_get")]
  public static extern int GRIB_NO_MORE_IN_SET_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_GEOCALCULUS_PROBLEM_get")]
  public static extern int GRIB_GEOCALCULUS_PROBLEM_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_OUT_OF_MEMORY_get")]
  public static extern int GRIB_OUT_OF_MEMORY_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_READ_ONLY_get")]
  public static extern int GRIB_READ_ONLY_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_ARGUMENT_get")]
  public static extern int GRIB_INVALID_ARGUMENT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NULL_HANDLE_get")]
  public static extern int GRIB_NULL_HANDLE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_SECTION_NUMBER_get")]
  public static extern int GRIB_INVALID_SECTION_NUMBER_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_VALUE_CANNOT_BE_MISSING_get")]
  public static extern int GRIB_VALUE_CANNOT_BE_MISSING_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_LENGTH_get")]
  public static extern int GRIB_WRONG_LENGTH_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_TYPE_get")]
  public static extern int GRIB_INVALID_TYPE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_STEP_get")]
  public static extern int GRIB_WRONG_STEP_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_STEP_UNIT_get")]
  public static extern int GRIB_WRONG_STEP_UNIT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_FILE_get")]
  public static extern int GRIB_INVALID_FILE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_GRIB_get")]
  public static extern int GRIB_INVALID_GRIB_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_INDEX_get")]
  public static extern int GRIB_INVALID_INDEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_ITERATOR_get")]
  public static extern int GRIB_INVALID_ITERATOR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_KEYS_ITERATOR_get")]
  public static extern int GRIB_INVALID_KEYS_ITERATOR_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_NEAREST_get")]
  public static extern int GRIB_INVALID_NEAREST_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_ORDERBY_get")]
  public static extern int GRIB_INVALID_ORDERBY_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_MISSING_KEY_get")]
  public static extern int GRIB_MISSING_KEY_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_OUT_OF_AREA_get")]
  public static extern int GRIB_OUT_OF_AREA_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_CONCEPT_NO_MATCH_get")]
  public static extern int GRIB_CONCEPT_NO_MATCH_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NO_DEFINITIONS_get")]
  public static extern int GRIB_NO_DEFINITIONS_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_TYPE_get")]
  public static extern int GRIB_WRONG_TYPE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_END_get")]
  public static extern int GRIB_END_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NO_VALUES_get")]
  public static extern int GRIB_NO_VALUES_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_WRONG_GRID_get")]
  public static extern int GRIB_WRONG_GRID_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_END_OF_INDEX_get")]
  public static extern int GRIB_END_OF_INDEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_NULL_INDEX_get")]
  public static extern int GRIB_NULL_INDEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_PREMATURE_END_OF_FILE_get")]
  public static extern int GRIB_PREMATURE_END_OF_FILE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INTERNAL_ARRAY_TOO_SMALL_get")]
  public static extern int GRIB_INTERNAL_ARRAY_TOO_SMALL_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_MESSAGE_TOO_LARGE_get")]
  public static extern int GRIB_MESSAGE_TOO_LARGE_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_CONSTANT_FIELD_get")]
  public static extern int GRIB_CONSTANT_FIELD_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_SWITCH_NO_MATCH_get")]
  public static extern int GRIB_SWITCH_NO_MATCH_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_UNDERFLOW_get")]
  public static extern int GRIB_UNDERFLOW_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_MESSAGE_MALFORMED_get")]
  public static extern int GRIB_MESSAGE_MALFORMED_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_CORRUPTED_INDEX_get")]
  public static extern int GRIB_CORRUPTED_INDEX_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_BPV_get")]
  public static extern int GRIB_INVALID_BPV_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_DIFFERENT_EDITION_get")]
  public static extern int GRIB_DIFFERENT_EDITION_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_VALUE_DIFFERENT_get")]
  public static extern int GRIB_VALUE_DIFFERENT_get();

  [global::System.Runtime.InteropServices.DllImport("Grib.Api.Native.dll", EntryPoint="CSharp_GRIB_INVALID_KEY_VALUE_get")]
  public static extern int GRIB_INVALID_KEY_VALUE_get();
}

}
