/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Grib.Api.Interop.SWIG {

public class GribUtilPackingSpec : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GribUtilPackingSpec(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GribUtilPackingSpec obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GribUtilPackingSpec() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          GribApiProxyPINVOKE.delete_GribUtilPackingSpec(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int packingType {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_packingType_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_packingType_get(swigCPtr);
      return ret;
    } 
  }

  public int packing {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_packing_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_packing_get(swigCPtr);
      return ret;
    } 
  }

  public int boustrophedonic {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_boustrophedonic_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_boustrophedonic_get(swigCPtr);
      return ret;
    } 
  }

  public int editionNumber {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_editionNumber_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_editionNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int accuracy {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_accuracy_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_accuracy_get(swigCPtr);
      return ret;
    } 
  }

  public int bitsPerValue {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_bitsPerValue_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_bitsPerValue_get(swigCPtr);
      return ret;
    } 
  }

  public int decimalScaleFactor {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_decimalScaleFactor_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_decimalScaleFactor_get(swigCPtr);
      return ret;
    } 
  }

  public int computeLaplacianOperator {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_computeLaplacianOperator_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_computeLaplacianOperator_get(swigCPtr);
      return ret;
    } 
  }

  public int truncateLaplacian {
	set
	{
		GribApiProxyPINVOKE.GribUtilPackingSpec_truncateLaplacian_set(swigCPtr, value);
	} 
	get
	{
		return GribApiProxyPINVOKE.GribUtilPackingSpec_truncateLaplacian_get(swigCPtr);
	} 
  }

  public double laplacianOperator {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_laplacianOperator_set(swigCPtr, value);
    } 
    get {
      double ret = GribApiProxyPINVOKE.GribUtilPackingSpec_laplacianOperator_get(swigCPtr);
      return ret;
    } 
  }

  public int deleteLocalDefinition {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_deleteLocalDefinition_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_deleteLocalDefinition_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_grib_values extraSettings {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_extraSettings_set(swigCPtr, SWIGTYPE_p_grib_values.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = GribApiProxyPINVOKE.GribUtilPackingSpec_extraSettings_get(swigCPtr);
      SWIGTYPE_p_grib_values ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_grib_values(cPtr, false);
      return ret;
    } 
  }

  public int extraSettingsCount {
    set {
      GribApiProxyPINVOKE.GribUtilPackingSpec_extraSettingsCount_set(swigCPtr, value);
    } 
    get {
      int ret = GribApiProxyPINVOKE.GribUtilPackingSpec_extraSettingsCount_get(swigCPtr);
      return ret;
    } 
  }

  public GribUtilPackingSpec() : this(GribApiProxyPINVOKE.new_GribUtilPackingSpec(), true) {
  }

}

}
