set( ECBUILD_MAJOR_VERSION "1" )
set( ECBUILD_MINOR_VERSION "8" )
set( ECBUILD_PATCH_VERSION "0" )

set( ECBUILD_VERSION_STR  "1.8.0" )

set( ECBUILD_MACRO_VERSION "${ECBUILD_MAJOR_VERSION}.${ECBUILD_MINOR_VERSION}" )
